## Environment
environment: production

url    : "//jonsuh.com"
url_protocol: "https:"
labs_url: "http://labs.jonsuh.com"
cdn_url: ""

paginate   : 10
limit_posts: 0
future     : false
unpublished: false